/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker"
// tslint:disable:object-literal-key-quotes

export const TDevmoji = t.iface([], {
  code: "string",
  emoji: t.opt("string"),
  gitmoji: t.opt("string"),
  description: t.opt("string"),
})

export const ConfigOptions = t.iface([], {
  types: t.array("string"),
  devmoji: t.array("TDevmoji"),
})

const exportedTypeSuite: t.ITypeSuite = {
  TDevmoji,
  ConfigOptions,
}
export default exportedTypeSuite
